import {StyleSheet} from 'react-native';
import {colorCode} from './colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colorCode.lightGrey,
  },
  bold: {
    fontSize: 14,
    fontFamily: 'Montserrat-Bold',
  },
  bigTitle: {
    fontSize: 20,
    fontFamily: 'Montserrat-Bold',
  },
  subTitle: {
    fontSize: 14,
    fontFamily: 'Montserrat-Regular',
  },
  sectionTitle: {
    fontSize: 12,
    padding: 10,
    fontFamily: 'Montserrat-Regular',
    color: colorCode.medGrey,
    textTransform: 'uppercase',
  },
  count: {
    fontSize: 24,
    fontFamily: 'Montserrat-Black',
    paddingVertical: 5,
  },
  error: {
    fontSize: 14,
    padding: 10,
    fontFamily: 'Montserrat-Regular',
    color: 'red',
  },
  white: {
    color: colorCode.white,
  },
  grey: {
    color: '#475464',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  ctr: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  btw: {
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  pv: {
    paddingVertical: 20,
  },
  ph: {
    paddingHorizontal: 10,
  },
  sectionPadding: {
    paddingHorizontal: 15,
  },
  card: {
    width: '85%',
    padding: 20,
    paddingVertical: 10,
    alignSelf: 'center',
    borderRadius: 5,
    marginVertical: 4,
  },
  input: {
    width: '100%',
    marginBottom: 10,
    paddingVertical: 10,
    alignSelf: 'center',
    borderBottomWidth: 1,
    borderBottomColor: colorCode.brand,
    fontSize: 24,
    fontFamily: 'Montserrat-Black',
  },
  circleButton: {
    borderRadius: 100,
    width: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowCard: {
    width: 300,
    backgroundColor: 'gold',
    borderRadius: 5,
    padding: 20,
    height: 300,
    marginRight: 10,
  },
  btn: {
    marginTop: 20,
    paddingVertical: 20,
    borderRadius: 5,
    textAlign: 'center',
    alignItems: 'center',
    backgroundColor: colorCode.tomato,
    width: '90%',
    alignSelf: 'center',
  },
  leftCircle: {
    width: 30,
    height: 30,
    borderRadius: 30,
    position: 'absolute',
    left: -20,
    bottom: '35%',
    backgroundColor: colorCode.white,
  },
  absLine: {
    width: '100%',
    height: 30,
    position: 'absolute',
    left: 20,
    bottom: '30%',
    alignItems: 'center',
  },
  rightCircle: {
    width: 30,
    height: 30,
    borderRadius: 30,
    position: 'absolute',
    right: -20,
    bottom: '35%',
    backgroundColor: colorCode.white,
  },
  horizontalCard: {
    backgroundColor: colorCode.brand,
    borderRadius: 25,
    margin: 1,
    position: 'relative',
    overflow: 'hidden',
  },
  abs: {
    backgroundColor: 'rgba(0,0,0,0.5)',
    position: 'absolute',
    top: 0,
    left: 0,
    justifyContent: 'space-around',
    width: '100%',
    height: '100%',
    padding: 20,
  },
  bg: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  tag: {
    backgroundColor: colorCode.black,
    borderRadius: 20,
    marginRight: 5,
    flexDirection: 'row',
    padding: 4,
    paddingHorizontal: 10,
    borderWidth: 2,
    borderColor: colorCode.white,
  },
  tagText: {
    fontSize: 14,
    paddingLeft: 5,
    color: colorCode.white,
    fontFamily: 'Montserrat-Bold',
  },
  imageCard: {
    height: 450,
  },
  borderBottom: {
    backgroundColor: '#E5E4EB',
    width: '95%',
    alignSelf: 'center',
    height: 1,
    marginVertical: 20,
  },
  detailsTitle: {
    fontSize: 16,
    fontFamily: 'Montserrat-Medium',
  },
  verticalCard: {
    shadowColor: '#E5E5E5',
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 0.5,
    shadowRadius: 30,
    elevation: 10,
    height: 350,
    marginVertical: 10,
    paddingHorizontal: 10,
  },
  paraText: {
    fontSize: 14,
    paddingHorizontal: 10,
    lineHeight: 24,
    fontFamily: 'Montserrat-Regular',
  },
  purchaseCard: {
    backgroundColor: colorCode.brand,
    width: '90%',
    alignSelf: 'center',
    borderRadius: 10,
    height: 300,
    padding: 20,
  },
  pay: {
    shadowColor: '#E5E5E5',
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 10,
    width: '27.5%',
    padding: 10,
    borderRadius: 10,
    backgroundColor: '#fff',
    marginHorizontal: 10,
  },
  btnRound: {
    backgroundColor: '#11D0A2',
    width: '85%',
    alignSelf: 'center',
    padding: 15,
    borderRadius: 40,
    marginVertical: 20,
  },
  btnText: {
    color: colorCode.white,
    fontFamily: 'Montserrat-Bold',
    textTransform: 'uppercase',
    textAlign: 'center',
  },
});
